name: Test iOS Fastlane Pipeline

on:
  workflow_dispatch:

jobs:
  ios:
    uses: mieweb/sharedactions/.github/workflows/ios-meteor.yml@v1
    with:
      app_identifier: org.mieweb.os.dev
      app_name:       MIEAuth Opensource Beta
      meteor_server:  https://mieauth-dev.os.mieweb.org
    secrets: inherit
