name: Test iOS Fastlane Pipeline

on:
  workflow_dispatch:

jobs:
  ios:
    uses: mieweb/sharedactions/.github/workflows/ios-meteor.yml@v1
    with:
      app_identifier:                org.mieweb.os.dev
      app_name:                      MIEAuth Opensource Beta
      meteor_server:                 https://mieauth-dev.os.mieweb.org
      firebase_ios_config_base64:    ${{ secrets.FIREBASE_IOS_DEV_PLIST_BASE64 }}
      firebase_android_config_base64: ${{ secrets.FIREBASE_SERVICES_PROD }}
    secrets: inherit
